distributable:
  url: https://github.com/ReagentX/imessage-exporter/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/imessage-exporter

versions:
  github: ReagentX/imessage-exporter

companions:
  ffmpeg.org: "*"
  imagemagick.org: "*"

build:
  dependencies:
    rust-lang.org: ">=1.95" # since v4.1.0
    rust-lang.org/cargo: "*"
  working-directory: imessage-exporter
  script:
    # version unset
    - sed -i 's/^version = ".*"$/version = "{{version}}"/' Cargo.toml
    - cargo install --locked --path . --root {{prefix}}

test:
  dependencies:
    curl.se: "*"
  script:
    - test "$(imessage-exporter --version)" = "iMessage Exporter {{version}}"
    - curl -LSsO https://raw.githubusercontent.com/ReagentX/imessage-exporter/refs/tags/{{version.tag}}/imessage-database/test_data/db/test.db
    - imessage-exporter --diagnostics --db-path test.db 2>&1 | tee out
    - grep 'iMessage Database Diagnostics' out
