distributable:
  url: https://github.com/chmln/sd/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/sd

versions:
  github: chmln/sd

build:
  dependencies:
    rust-lang.org: ">=1.65"
    rust-lang.org/cargo: "*"
    github.com/mikefarah/yq: ">=4" # safe-edit toml version field
  script:
    # missed version bump; workspace.package for >=1.1.0, package for older
    - yq -i '(.workspace.package // .package).version = "{{version}}"' Cargo.toml
    - run: cargo install --locked --path . --root {{prefix}}
      if: <1.1.0
    - run: cargo install --locked --path sd-cli --root {{prefix}}
      if: ">=1.1.0"

test: test "$(sd --version)" = "sd {{version}}"
