distributable:
  url: https://github.com/pkolaczk/fclones/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

provides:
  - bin/fclones

versions:
  github: pkolaczk/fclones
  strip: /v/

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script:
    cargo install --locked --path fclones --root {{prefix}}

test: |
  fclones --version | grep {{version}}
