distributable:
  url: https://github.com/pkolaczk/fclones/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

provides:
  - bin/fclones

versions:
  github: pkolaczk/fclones

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script: cargo install --locked --path fclones --root {{prefix}}

test:
  - fclones --version | tee out
  - grep {{version}} out
