distributable:
  url: https://github.com/sbt/sbt/releases/download/v{{version}}/sbt-{{version}}.tgz
  strip-components: 1

warnings:
  - vendored

versions:
  github: sbt/sbt

dependencies:
  openjdk.org: "*"

build:
  - mkdir -p {{prefix}}/bin {{prefix}}/etc
  - run:
      - sed -i 's,/etc/sbt/,\$(pwd)/../etc/,g' sbt
      - install sbt sbt-launch.jar {{prefix}}/bin/
    working-directory: bin

provides:
  - bin/sbt

test:
  - run:
      # v2 requires newer glibc
      - if test {{hw.platform}} = linux; then exit 0; fi

      - touch build.sbt
    if: ">=2"
  - sbt --sbt-create about | grep {{version}}
