distributable:
  url: git+https://github.com/JamesWoolfenden/pike
  ref: ${{version.tag}}

versions:
  github: JamesWoolfenden/pike

build:
  dependencies:
    go.dev: ^1.22
    git-scm.org: "*"
  script:
    - run: ./set-version.sh
      if: <0.4.7
    - go mod download
    - go build -v -ldflags="$GO_LDFLAGS" -o {{prefix}}/bin/pike main.go
  env:
    CGO_ENABLED: 0
    GO_LDFLAGS:
      - -extldflags=-static
      - -w
      - -s
      # since 0.4.7
      - -X github.com/jameswoolfenden/pike/src.Version=v{{version}}

provides:
  - bin/pike

test:
  - test "$(pike --version)" = "pike version v{{version}}"
  - pike scan -d .
