distributable:
  url: https://github.com/aws/aws-sam-cli/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: aws/aws-sam-cli

dependencies:
  pkgx.sh: ">=1"

build:
  dependencies:
    python.org: ~3.13
    rust-lang.org: "*"
  env:
    OPENSSL_STATIC: 1
    OPENSSL_DIR: "{{pkgx.prefix}}/openssl.org/v3"
  script:
    - pkgx +openssl.org^3
    - bkpyvenv stage {{prefix}} {{version}}
    - ${{prefix}}/venv/bin/pip install .
    - bkpyvenv seal {{prefix}} sam

provides:
  - bin/sam

test:
  - sam --version | tee out
  - grep {{version}} out
  - sam validate --region us-east-1 2>&1 | tee out
  - grep 'is a valid SAM Template' out
