distributable:
  url: https://github.com/stepchowfun/toast/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/toast

versions:
  github: stepchowfun/toast

build:
  dependencies:
    rust-lang.org: ">=1.65"
    rust-lang.org/cargo: "*"
  script: cargo install --locked --path . --root {{prefix}}

test:
  - run: test "$(toast --version)" = "Toast {{version}}"
    if: <0.48.0
  - run: test "$(toast --version)" = "toast {{version}}"
    if: ">=0.48.0"
