#!/bin/sh

# or npx fails ※
# FIXME a patch to npm here then upstream would be preferable
mkdir -p ~/.local/lib

d="$(cd "$(dirname $0)"/.. && pwd)"
"$d"/tbin/npx "$@"

# ※ https://github.com/teaxyz/cli/issues/532
