#!/bin/sh

# or npx fails ※
# FIXME a patch to npm here then upstream would be preferable
mkdir -p ~/.local/lib

d="$(cd "$(dirname $0)" && pwd)"
exec "$d"/npm exec -- "$@"

# ※ https://github.com/teaxyz/cli/issues/532
