#!/bin/sh

# or npx fails ※
# FIXME a patch to npm here then upstream would be preferable
mkdir -p ~/.local/lib

d="$(cd "$(dirname $0)"/.. && pwd)"
exec "$d"/lib/node_modules/npm/bin/npx-cli.js "$@"

# ※ https://github.com/teaxyz/cli/issues/532
