distributable:
  url: git+https://github.com/rustfs/cli
  ref: ${{ version.tag }}

versions:
  github: rustfs/cli

build:
  dependencies:
    rust-lang.org/cargo: "*"
  script: cargo install --locked --path crates/cli --root {{prefix}}

provides:
  - bin/rc

test: rc --version | grep "rc {{version}}"
