distributable:
  url: git+https://github.com/Netflix/vmaf.git
  ref: ${{version.tag}}

versions:
  github: Netflix/vmaf

build:
  dependencies:
    mesonbuild.com: "*"
    ninja-build.org: "*"
    nasm.us: "*"
  working-directory: libvmaf
  script:
    - meson --prefix={{prefix}} --buildtype=release build
    - meson compile -C build
    - meson install -C build

provides:
  - bin/vmaf

test:
  - run: cc $FIXTURE
    fixture:
      extname: c
      content: |
        #include <libvmaf/libvmaf.h>
        int main() {
          return 0;
        }
  - ./a.out
