distributable:
  url: https://github.com/rome/tools/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

provides:
  - bin/rome

versions:
  github: rome/tools
  strip: /v/

build:
  working-directory: crates/rome_cli
  dependencies:
    rust-lang.org: '>=1.65'
    rust-lang.org/cargo: '*'
    github.com/mikefarah/yq: '>=4' # safe-edit toml version field
  script:
    # shipped with a 0.0.0 placeholder version
    - yq -i '.package.version = "{{version}}"' Cargo.toml
    - cargo install --locked --path . --root {{prefix}}

test:
  script:
    - test "$(rome help | head -n1)" = "Rome v{{version}}"
