distributable:
  url: https://github.com/aws-cloudformation/cfn-lint/archive/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: aws-cloudformation/cfn-lint

dependencies:
  pkgx.sh: ">=1"
  pyyaml.org: "*"
  github.com/benjaminp/six: "*"

build:
  dependencies:
    rust-lang.org: "*"
    python.org: ~3.11
  script:
    # wrong version shipped
    - run: sed -i 's/__version__ = ".*"/__version__ = "{{version}}"/' version.py
      working-directory: src/cfnlint
    - bkpyvenv stage {{prefix}} {{version}}
    - ${{prefix}}/venv/bin/pip install .
    - bkpyvenv seal {{prefix}} cfn-lint

provides:
  - bin/cfn-lint

test:
  - run: cfn-lint --update-specs
  - run: cfn-lint $FIXTURE
    fixture:
      extname: yml
      content: |
        ---
        AWSTemplateFormatVersion: '2010-09-09'
        Resources:
          # Helps tests map resource types
          IamPipeline:
            Type: "AWS::CloudFormation::Stack"
            Properties:
              TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/bucket-dne-${AWS::Region}/${AWS::AccountId}/pipeline.yaml'
              Parameters:
                DeploymentName: iam-pipeline
                Deploy: 'auto'
  - cfn-lint -v | grep {{version}}
