display-name: librepo
summary: Library for downloading linux repository metadata and packages

distributable:
  url: https://github.com/rpm-software-management/librepo/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

platforms: [linux]

versions:
  github: rpm-software-management/librepo

dependencies:
  gnome.org/glib: "*"
  gnome.org/libxml2: "*"
  savannah.nongnu.org/attr: "*"
  curl.se: "*"
  openssl.org: "*"
  rpm.org/rpm: "*"
  rpm.org/popt: "*"
  zlib.net: "*"
  pcre.org/v2: "*"
  sourceware.org/libffi: "*"

build:
  dependencies:
    cmake.org: ">=3.16"
    gnu.org/gcc: "^14"
    python.org: ">=3.9"
  env:
    CMAKE_ARGS:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX={{prefix}}
      - -DUSE_GPGME=OFF
      - -DWITH_ZCHUNK=OFF
      - -DENABLE_TESTS=OFF
      - -DENABLE_PYTHON=OFF
      - -DENABLE_DOCS=OFF
  script:
    - cmake -S . -B build $CMAKE_ARGS
    - cmake --build build  
    - cmake --install build
    - run: |
        if [ -f "librepo.so.0" ]; then
          mv "librepo.so.0" "librepo.so.0.{{version}}"
          ln -sf "librepo.so.0.{{version}}" "librepo.so.0"
          ln -sf "librepo.so.0" "librepo.so"
        fi
      working-directory: ${{prefix}}/lib

test:
  - test -f {{prefix}}/lib/librepo.so.0.{{version}}
  - test -L {{prefix}}/lib/librepo.so.0
  - test -L {{prefix}}/lib/librepo.so
  - test -f {{prefix}}/include/librepo/librepo.h
  - run: cc $FIXTURE -o test $(pkg-config --cflags --libs librepo)
    fixture:
      extname: c
      content: |
        #include <librepo/librepo.h>

        int main(void) {
          return 0;
        }
  - ./test
