distributable:
  url: https://github.com/reacherhq/check-if-email-exists/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/check_if_email_exists

versions:
  github: reacherhq/check-if-email-exists

dependencies:
  openssl.org: ^1.1

build:
  working-directory: cli
  dependencies:
    rust-lang.org: '>=1.65'
    rust-lang.org/cargo: '*'
    perl.org: '*'
    github.com/mikefarah/yq: '>=4' # safe-edit toml version/deps
  script:
    # forgot to bump the version (per-file: multi-file `yq -i` corrupts toml)
    - run:
        - yq -i '.package.version = "{{version}}"' core/Cargo.toml
        - yq -i '.package.version = "{{version}}"' cli/Cargo.toml
        - yq -i '.package.version = "{{version}}"' backend/Cargo.toml
      working-directory: ..
    # missing feature needed to build
    - run: yq -i '.dependencies["check-if-email-exists"].features = ["sentry"]' Cargo.toml
      if: ^0.10
    - cargo install --path . --root {{prefix}}

test: test "$(check_if_email_exists --version)" = "check-if-email-exists-cli {{version}}"
