distributable:
  url: https://github.com/hadolint/hadolint/archive/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: hadolint/hadolint

build:
  dependencies:
    haskell.org: ~9.10 # as of 2.13.1
    haskell.org/cabal: ^3
    git-scm.org: ^2 # cabal needs it for this one
  env:
    ARGS:
      - --jobs={{hw.concurrency}}
      - --install-method=copy
      - --installdir={{prefix}}/bin
  script:
    - cabal v2-update
    - cabal v2-install $ARGS

provides:
  - bin/hadolint

test:
  script:
    - hadolint --version | grep {{version}}
    - run: echo $(hadolint $FIXTURE || true) | grep DL3006
      fixture: |
        FROM debian
