distributable:
  url: https://github.com/rpm-software-management/rpm-sequoia/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

display-name: rpm-sequoia

versions:
  github: rpm-software-management/rpm-sequoia/tags

platforms: [linux]

build:
  dependencies:
    rust-lang.org: ">=1.85"
    pkgx.sh: ">=1"
  env:
    OPENSSL_DIR: "{{pkgx.prefix}}/openssl.org/v3"
    OPENSSL_STATIC: "1"
    PREFIX: "{{prefix}}"
  script:
    - pkgx +openssl.org^3.0.7
    - cargo build --release --no-default-features --features crypto-openssl
    - run: install -Dm755 $SRCROOT/target/release/librpm_sequoia.so librpm_sequoia.so
      working-directory: ${{prefix}}/lib/
    - run: ln -s librpm_sequoia.so librpm_sequoia.so.1
      working-directory: ${{prefix}}/lib
      if: linux
    # OPENSSL_STATIC: don't advertise a libssl pkg-config dep
    - run: sed -e 's|/usr/local|{{prefix}}|' -e 's/^Requires.private:.*/Requires.private:/' $SRCROOT/target/release/rpm-sequoia.pc >rpm-sequoia.pc
      working-directory: ${{prefix}}/lib/pkgconfig/

test:
  dependencies:
    gnu.org/gcc: "*"
    freedesktop.org/pkg-config: "*"
  script:
    - test -f {{prefix}}/lib/librpm_sequoia.so
    - test -f {{prefix}}/lib/pkgconfig/rpm-sequoia.pc
    - pkg-config --print-errors --exists rpm-sequoia
    # Test C linkage with the rpm-sequoia library
    - run: gcc -v $FIXTURE -o test_link $(pkg-config --cflags --libs rpm-sequoia)
      fixture:
        extname: c
        content: |
          #include <stdio.h>

          int main(void) {
            puts("rpm-sequoia library linkage test passed");
            return 0;
          }
    - ./test_link
