distributable:
  url: https://github.com/containerd/nerdctl/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

display-name: nerdctl

versions:
  github: containerd/nerdctl/releases

platforms:
  - linux/x86-64
  - linux/aarch64

build:
  dependencies:
    go.dev: '*'
  script:
    - go build -o {{prefix}}/bin/nerdctl ./cmd/nerdctl
  skip: fix-patchelf

provides:
  - bin/nerdctl

test:
  - nerdctl --version | grep "nerdctl version {{version}}"
