distributable:
  url: https://github.com/certbot/certbot/archive/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: certbot/certbot

dependencies:
  python.org: ~3.11

build:
  dependencies:
    pkgx.sh: ">=1"
  script:
    - pkgx +openssl.org^3
    - python-venv.sh {{prefix}}/bin/certbot
  env:
    SRCROOT: $SRCROOT/certbot
    OPENSSL_STATIC: 1
    OPENSSL_DIR: "{{pkgx.prefix}}/openssl.org/v3"

provides:
  - bin/certbot

test:
  script:
    - certbot --version | grep {{version}}
    - mkdir certbot
    - chmod 777 certbot
    - certbot certificates $ARGS | grep "No certificates found."
  env:
    ARGS:
      - --config-dir="certbot/config"
      - --work-dir="certbot"
      - --logs-dir="certbot/log"
