distributable:
  url: git+https://github.com/VikParuchuri/surya.git
  ref: ${{version.tag}}

display-name: Surya

versions:
  github: VikParuchuri/surya

# things like torch have dropped darwin/x86-64 support, so we need to exclude that platform
platforms:
  - linux
  - darwin/aarch64

dependencies:
  pkgx.sh: ">=1"
  linux:
    mesa3d.org: ^23.3
    gnome.org/glib: ^2
    mupdf.com: "*"

build:
  dependencies:
    python.org: ~3.11
    python-poetry.org: ^1.7
  script:
    - run: bkpyvenv stage --engine=poetry {{prefix}} {{version}}
      if: <0.20
    - run: bkpyvenv stage {{prefix}} {{version}}
      if: ">=0.20"

    # cv2 libs are compiled for MACOSX_DEPLOYMENT_TARGET=12.0
    - run: |
        if test "{{hw.platform}}" = "darwin"; then
          poetry config --local installer.no-binary opencv-python
        fi
      if: <0.20

    # torch removed darwin/x86-64 binaries in 2.3.0
    # https://github.com/pytorch/pytorch/pull/116726
    - run: |
        if test "{{hw.platform}}/{{hw.arch}}" = "darwin/x86-64"; then
          sed -i 's/^torch.*/torch = "=2.2.2"/' pyproject.toml
          poetry lock
        fi
      if: ">=0.4.4<0.20"

    # pymupdf==1.25.3 has build failures on linux/aarch64
    - run: |
        if test "{{hw.platform}}/{{hw.arch}}" = "linux/aarch64"; then
          poetry add 'pymupdf==1.25.2'
        fi
      if: <0.20

    - run: poetry install
      if: <0.20
    - run: ${{prefix}}/venv/bin/pip install .
      if: ">=0.20"

    # not found in some installs post 0.5
    - run: poetry add 'numpy<2'
      if: ">=0.5<0.20"

    - run: bkpyvenv seal --engine=poetry {{prefix}} surya_detect
      if: <0.20
    - run: bkpyvenv seal {{prefix}} surya_detect
      if: ">=0.20"

provides:
  - bin/surya_detect

test:
  dependencies:
    curl.se: "*"
  script:
    - curl -L "https://raw.githubusercontent.com/VikParuchuri/surya/{{version.tag}}/static/images/excerpt.png" -o test.png
    - surya_detect ./test.png --images
    - |
      grep -F '"bboxes": [{' results/surya/test/results.json
    - |
      grep -F '"confidence":' results/surya/test/results.json
