versions:
  github: golangci/golangci-lint

warnings:
  - vendored

build:
  dependencies:
    curl.se: "*"
  working-directory: ${{prefix}}
  script: curl -sSfL "https://golangci-lint.run/install.sh" | sh -s -- -b ./bin v{{version}}

provides:
  - bin/golangci-lint

test:
  # FIXME: this works around a bug introduced in 1.53.0
  # https://github.com/golangci/golangci-lint/issues/3862#issuecomment-1572973588
  dependencies:
    go.dev: ^1.24
  script: golangci-lint help linters
  env:
    GOROOT: $(go env GOROOT)
