distributable:
  url: https://github.com/spider-rs/spider/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/spider

versions:
  github: spider-rs/spider

build:
  dependencies:
    rust-lang.org: '>=1.81'
    rust-lang.org/cargo: '*'
  script:
    # needs openssl 3 on linux, but our rust locks us to 1.1.1
    - run: source <(pkgx +openssl^3)
      if: linux
    # -shared and -pie don't mix
    - run: install -Dm755 $PROP cc
      prop: |
        #!/bin/bash
        # Capture all arguments into an array
        ARGS=("$@")

        # Check if the '-shared' flag is present in the arguments
        if printf "%s\n" "${ARGS[@]}" | grep -q -e '-shared'; then

          # Use a loop to filter out the '-pie' flag from the arguments
          FILTERED_ARGS=()
          for arg in "${ARGS[@]}"; do
            if [ "$arg" != "-pie" ]; then
              FILTERED_ARGS+=("$arg")
            fi
          done

          # Pass the filtered arguments to clang
          exec clang "${FILTERED_ARGS[@]}"
        else
          # Pass the original arguments to clang
          exec clang "${ARGS[@]}"
        fi
      working-directory: $HOME/.local/bin
      if: linux/x86-64
    - cargo install --locked --path spider_cli --root {{prefix}} --features smart
  env:
    linux:
      # since we are tricking _ourselves_ into using openssl 3, we need to
      # link it statically.
      OPENSSL_STATIC: 1
      OPENSSL_DIR: ${{pkgx.prefix}}/openssl.org/v3/
      OPENSSL_NO_VENDOR: 1
    linux/x86-64:
      RUSTFLAGS: -Crelocation-model=pic -Clink-arg=-pie -Clink-arg=-fPIC
      PATH: $HOME/.local/bin:$PATH

test: spider -v --url https://choosealicense.com scrape
