distributable:
  url: https://github.com/vlang/v/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

versions:
  github: vlang/v

interprets:
  extensions: v
  args: [v, run]

build:
  dependencies:
    git-scm.org: "*"
  script:
    # fixed in https://github.com/vlang/v/commit/ca484430e0380a3fc591b842aadda4fe18deaae5
    - run: git apply props/int-types.diff
      if: =0.3.2

    - make prod=1

    - mkdir -p {{prefix}}/libexec
    - cp -R cmd thirdparty v v.mod vlib {{prefix}}/libexec/

    - run: ln -s ../libexec/v v
      working-directory: ${{prefix}}/bin

test:
  env:
    darwin:
      LDFLAGS: -Wl,-rpath,{{prefix}}/../..
  script:
    - run: test "$(v run $FIXTURE)" = "Hello, World!"
      fixture:
        extname: v
        content: println('Hello, World!')

provides:
  - bin/v
