distributable:
  url: https://github.com/go-acme/lego/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: go-acme/lego

build:
  dependencies:
    go.dev: ^1.25

  env:
    CGO_ENABLED: 0
    GO11MODULE: on
    GO_LDFLAGS:
      - -s
      - -w
      - -X main.version={{ version }}
    linux:
      GO_LDFLAGS:
        - -buildmode=pie
  script:
    - run: go build -v -ldflags="${GO_LDFLAGS}" -o "{{ prefix }}"/bin/lego ./cmd/lego
      if: <5
    - run: go build -v -ldflags="${GO_LDFLAGS}" -o "{{ prefix }}"/bin/lego .
      if: ">=5"

provides:
  - bin/lego

test: test "$(lego --version|cut -d ' ' -f 3)" = {{version}}
