distributable: ~

warnings:
  - vendored

versions:
  github: borkdude/jet

provides:
  - bin/jet

build:
  dependencies:
    curl.se: "*"
  working-directory: ${{prefix}}/bin
  script: curl -LsS https://github.com/borkdude/jet/releases/download/{{version.tag}}/jet-{{version}}-$PLATFORM-$ARCH.tar.gz | tar zxf -
  env:
    darwin:
      PLATFORM: macos
    linux:
      PLATFORM: linux
    aarch64:
      ARCH: aarch64
    x86-64:
      ARCH: amd64

test: test "$(jet --version)" = "{{version}}"
