distributable:
  url: https://github.com/theryangeary/choose/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

provides:
  - bin/choose

versions:
  github: theryangeary/choose
  strip: /v/

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script:
    cargo install --locked --path . --root {{prefix}}

test: |
  choose --version | grep {{version}}
  test "$(echo 'a b c' | choose 1)" = "b"
