distributable:
  url: https://github.com/nextest-rs/nextest/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

provides:
  - bin/cargo-nextest

versions:
  github: nextest-rs/nextest
  strip: /^cargo-nextest-/

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script: cargo install --locked --path cargo-nextest --root {{prefix}}

test:
  - cargo-nextest --version | tee out
  - grep {{version}} out
