distributable:
  url: https://registry.npmjs.org/pyright/-/pyright-{{version}}.tgz
  strip-components: 1

versions:
  npm: pyright

dependencies:
  nodejs.org: ^22.22.2 || ^24.15.0 || >=26.0.0 # as of 1.1.412

build:
  dependencies:
    npmjs.com: '*'
  script: npm i $ARGS .
  env:
    ARGS:
      - --ddd
      - --global
      - --prefix={{prefix}}
      - --install-links

provides:
  - bin/pyright

test:
  - run: (pyright $FIXTURE 2>&1 || true) | tee out.log
    fixture:
      content: |
        def wrong_types(a: int, b: int) -> str:
          return a + b
      extname: py
  - cat out.log | grep -E 'ype "int" (cannot be assigned to|is incompatible with|is not assignable to) return type "str"'
  - run: pyright $FIXTURE 2>&1 | grep '0 errors, 0 warnings, 0 informations'
    fixture:
      content: |
        def add(a: int, b: int) -> int:
          return a + b
      extname: py
  - pyright --version | grep {{version}}
