distributable:
  url: https://registry.npmjs.org/pnpm/-/pnpm-{{version}}.tgz
  strip-components: 1

versions:
  github: pnpm/pnpm
  ignore: /-\d+$/ # ignore pre-releases

provides:
  - bin/pnpm
  - bin/pnpx

dependencies:
  nodejs.org: "*"

build:
  script:
    - mkdir -p "{{prefix}}"
    - ln -s pnpm.cjs bin/pnpm
    - ln -s pnpx.cjs bin/pnpx
    - chmod +x bin/*
    - cp props/pnpmrc dist
    - cp -r bin dist package.json {{prefix}}

test:
  - run: pnpm doctor
    if: <11
  - pnpm add express
