distributable:
  url: https://registry.npmjs.org/pnpm/-/pnpm-{{version}}.tgz
  strip-components: 1

versions:
  npm: pnpm

provides:
  - bin/pnpm
  - bin/pnpx

dependencies:
  nodejs.org: ^18 || ^20 || ^22

build:
  script:
    mkdir -p "{{prefix}}"
    mv bin/pnpm.cjs bin/pnpm
    mv bin/pnpx.cjs bin/pnpx
    cp props/pnpmrc dist
    cp -r bin dist package.json {{prefix}}

test:
  - pnpm --version | grep {{version}}
  - pnpm doctor
