distributable:
  url: https://github.com/jdx/usage/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

provides:
  - bin/usage

versions:
  github: jdx/usage
  strip: /^v/

platforms:
  - linux
  - darwin

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script: cargo install --locked --path cli --root {{prefix}}

test:
  script:
    - usage --version | grep {{version}}
