distributable:
  url: https://github.com/stepchowfun/docuum/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/docuum

versions:
  github: stepchowfun/docuum

build:
  dependencies:
    rust-lang.org: ">=1.65"
    rust-lang.org/cargo: "*"
  script: cargo install --locked --path . --root {{prefix}}

test:
  - run: test "$(docuum --version)" = "Docuum {{version}}"
    if: <0.27
  - run: test "$(docuum --version)" = "docuum {{version}}"
    if: ">=0.27"
