#!/bin/sh
# inspired by: https://github.com/wuyuansushen/aria2c_TrackersList

set -e

cd "$(dirname "$0")"/..

if test -n $VERBOSE; then
  set -x
fi

clone_or_update() {
  if test -d trackers; then
    git fetch origin
    git reset --hard origin/main
  else
    git clone "https://github.com/ngosang/trackerslist.git" trackers
  fi
}

generate_output() {
  mkdir etc
  TRACKERS=$(grep -v '^#' "trackers/trackers_all.txt" | tr '\n' ',')
  echo "bt-tracker=${TRACKERS}" > etc/aria2.conf
}

if ! test -d models; then
  tea gum spin "cloning/updating aria2c tracker list" -- clone_or_update
  tea gum spin "configuring aria2c" -- generate_output

  tea gum format <<EoMD
  # downloading quantized LLaMA models
  models will be placed: `\~/.local/share/LLaMA/$VERSION\`
  > this may take a while…
EoMD

  tea aria2 \
    --dir="$HOME"/.local/share/LLaMA/$VERSION \
    --conf-file=etc/aria2.conf \
    --seed-time=0 \
    share/LLaMA-q4.torrent
fi
