#!/usr/bin/env sh

set -eu

# get this script's path
script_path="$(realpath "$0")"

# will be replaced during build
version="%%version%%"

temp_dir="$(mktemp -d -p /tmp "pkgx-kiro-cli-${version}-XXXXXXXXXX")"
trap 'rm -rf "${temp_dir}"' EXIT

arch="$(uname -m)"
download_url="https://desktop-release.q.us-east-1.amazonaws.com/${version}/kirocli-${arch}-linux.zip"
download_file="${temp_dir}/kiro-cli.zip"
archive_bin="kirocli/bin/kiro-cli"

curl -fL -# -o "${download_file}" "${download_url}"
unzip -q -o "${download_file}" -d "${temp_dir}" "${archive_bin}"
install -Dm755 "${temp_dir}/kirocli/bin/kiro-cli" "${script_path}"

rm -rf "${temp_dir}"

exec "${script_path}" "$@"
