distributable:
  url: https://github.com/longbridge/longbridge-terminal/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

display-name: longbridge

provides:
  - bin/longbridge

versions:
  github: longbridge/longbridge-terminal
  strip: /v/

build:
  dependencies:
    rust-lang.org: ^1.70
    rust-lang.org/cargo: "*"
  script: cargo install --locked --path . --root {{prefix}}

test:
  script: longbridge --version
