#!/bin/sh

set -e

workspace_directory="${XDG_DOCUMENTS_DIR:-$HOME/Documents}/Auto-GPT"

# if the data|plugins directories don’t exist auto-gpt bails
mkdir -p "$workspace_directory"/data "$workspace_directory"/plugins

# change to this directory because auto-gpt assumes it is running
# in its own checkout and is not suitable to be run from anywhere
cd "$workspace_directory"

exec "$VIRTUAL_ENV"/bin/python -m autogpt --workspace-directory="$workspace_directory" "$@"
