distributable:
  url: https://github.com/01mf02/jaq/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

provides:
  - bin/jaq

versions:
  github: 01mf02/jaq

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script: cargo install --locked --path jaq --root {{prefix}}

test:
  - jaq --version | tee out
  - grep {{version}} out
  - echo '{"a":1}' | jaq '.a' | grep '^1$'
