distributable:
  url: https://github.com/orf/gping/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

provides:
  - bin/gping

versions:
  github: orf/gping/tags
  strip: /^gping-v/

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script: cargo install --locked --path gping --root {{prefix}}

test:
  - gping --version | tee out
  - grep {{version}} out
