#!/bin/sh

d=$(dirname "$0")
etc="$d/../etc/gnupg"

export GNUPGHOME="${GNUPGHOME:-"$etc"}"

mkdir -p "$etc"
chmod 700 "$etc"
cat << EOF > "$etc"/gpg.conf
use-agent
pinentry-mode loopback
agent-program $d/gpg-agent
EOF

exec "$d"/gpg-exec "$@"