#!/bin/sh

set -e
test -n "$VERBOSE" && set -x

MODEL_NAME="base"
MODEL_DIR="$1"
VERSION="$2"

D="$(cd "$(dirname "$0")"/../tbin && pwd)"

mkdir -p "$MODEL_DIR"

# we have to move the script as it downloads relative to itself
cp "$D/download-ggml-model.sh" "$MODEL_DIR"
bash "$MODEL_DIR/download-ggml-model.sh" "$MODEL_NAME.en"
rm "$MODEL_DIR/download-ggml-model.sh"
