distributable:
  url: https://github.com/ansible/ansible-lint/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: ansible/ansible-lint

dependencies:
  pkgx.sh: ">=1"

build:
  dependencies:
    python.org: ~3.11
  script:
    - pkgx +openssl.org^3
    - bkpyvenv stage {{prefix}} {{version}}
    - ${{prefix}}/venv/bin/pip install .
    - bkpyvenv seal {{prefix}} ansible-lint
  env:
    OPENSSL_STATIC: 1
    OPENSSL_DIR: "{{pkgx.prefix}}/openssl.org/v3"

test:
  - run: cat $FIXTURE | sed '/^$/d' >test.toml
    fixture:
      extname: toml
      content: |
        [defaults]
        fast_caching_timeout=invalid-value
  - ansible-lint --project-dir . test.toml

provides:
  - bin/ansible-lint
