distributable:
  url: https://github.com/jj-vcs/jj/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

display-name: jj

versions:
  github: jj-vcs/jj/tags
  strip: /v/

provides:
  - bin/jj

build:
  dependencies:
    rust-lang.org: "*"
    rust-lang.org/cargo: "*"
  script: cargo install --locked --path cli --root {{prefix}} --bin jj

test:
  script: |
    {{prefix}}/bin/jj --version
