distributable:
  url: https://github.com/Yubico/yubikey-manager/archive/refs/tags/{{ version }}.tar.gz
  strip-components: 1

display-name: yubikey-manager

versions:
  github: Yubico/yubikey-manager

dependencies:
  python.org: ~3.11
  linux:
    pcsclite.apdu.fr: "^2"

build:
  dependencies:
    pip.pypa.io: "*"
    swig.org: "*"
  script:
    - pkgx +openssl.org^3
    - python-venv.sh {{prefix}}/bin/ykman
  env:
    OPENSSL_STATIC: 1
    OPENSSL_DIR: "{{pkgx.prefix}}/openssl.org/v3"

provides:
  - bin/ykman

test: ykman --version | grep {{version}}
