distributable:
  url: https://registry.npmjs.org/next/-/next-{{version}}.tgz
  strip-components: 1

display-name: next.js

versions:
  npm: next

dependencies:
  nodejs.org: ^20.9.0

build:
  dependencies:
    npmjs.com: ^11
  script:
    - npm install --global --prefix={{prefix}} --install-links .

provides:
  - bin/next

test:
  - next --version | grep {{version}}
  - next --help | grep -i usage
