distributable:
  url: https://github.com/warmcat/libwebsockets/archive/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: warmcat/libwebsockets/tags

dependencies:
  libuv.org: 1
  libevent.org: 2

build:
  dependencies:
    cmake.org: 3
  working-directory: build
  script:
    - cmake .. -DCMAKE_INSTALL_PREFIX="{{prefix}}" $ARGS
    - make --jobs {{ hw.concurrency }} install

    - run: sed -E -i -f $PROP LibwebsocketsTargets.cmake libwebsockets-config.cmake
      prop: |
        s:{{pkgx.prefix}}:\$\{_IMPORT_PREFIX\}/../..:g
        /^  INTERFACE_INCLUDE_DIRECTORIES/ s|/v([0-9]+)(\.[0-9]+)*[a-z]?/include|/v\1/include|g
        /^  INTERFACE_LINK_LIBRARIES/ s|/v([0-9]+)(\.[0-9]+)*[a-z]?/lib|/v\1/lib|g
        /^set\(LIBWEBSOCKETS_INCLUDE_DIRS/ s|/v([0-9]+)(\.[0-9]+)*[a-z]?/include|/v\1/include|g
      working-directory: ${{prefix}}/lib/cmake/libwebsockets
  env:
    ARGS:
      - -DLWS_IPV6=ON
      - -DLWS_WITH_HTTP2=ON
      - -DLWS_WITH_EVLIB_PLUGINS=OFF
      - -DLWS_WITH_LIBEVENT=ON
      - -DLWS_WITH_LIBUV=ON
      - -DLWS_WITH_PLUGINS=ON
      - -DLWS_WITHOUT_TESTAPPS=ON
      - -DLWS_UNIX_SOCK=ON

test:
  - run: cc $FIXTURE -lwebsockets
    fixture:
      extname: c
      contents: |
          #include <openssl/ssl.h>
          #include <libwebsockets.h>

          int main() {
            struct lws_context_creation_info info;
            memset(&info, 0, sizeof(info));
            struct lws_context *context;
            context = lws_create_context(&info);
            lws_context_destroy(context);
            return 0;
          }

  - ./a.out
