distributable:
  url: http://ftp.rpm.org/releases/rpm-{{version.major}}.{{version.minor}}.x/rpm-{{version}}.tar.bz2
  strip-components: 1

display-name: rpm

platforms: [linux] # they don't officially support darwin, and it's a bear to patch

versions:
  github: rpm-software-management/rpm
  strip:
    - /^rpm-/
    - /-release$/

dependencies:
  lua.org: "5.4"
  gnu.org/gmp: "*"
  libarchive.org: "*"
  darwinsys.com/file: "*"
  rpm.org/popt: "*"
  gnu.org/readline: "*"
  invisible-island.net/ncurses: "*"
  sqlite.org: "*"
  tukaani.org/xz: "*"
  facebook.com/zstd: "*"
  elfutils.org: "*"
  gnu.org/gcc/libstdcxx: ">=15"
  gnu.org/gcc/libgomp: ">=15"
  openssl.org: "*"

build:
  dependencies:
    cmake.org: ^3.18
    lua.org: "5.4"
    gnu.org/gettext: "*"
    invisible-island.net/ncurses: "*"
    python.org: ">=3.10"
    sr.ht/scdoc: "*"
    curl.se: "*"
    gnu.org/tar: "*"
    gnu.org/gcc: 15
    gnu.org/binutils: ~2.44
    rust-lang.org: ">=1.85"
    openssl.org: "*"
  env:
    CC: gcc
    CXX: g++
    OPENSSL_DIR: "{{deps.openssl.org}}"
    LDFLAGS: "-L{{deps.openssl.org}}/lib"
    CPPFLAGS: "-I{{deps.openssl.org}}/include"
    PKG_CONFIG_PATH: "{{deps.openssl.org}}/lib/pkgconfig:$PKG_CONFIG_PATH"
    LD_LIBRARY_PATH: "{{deps.openssl.org}}/lib:$LD_LIBRARY_PATH"
    CMAKE_ARGS:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_C_COMPILER=gcc
      - -DCMAKE_CXX_COMPILER=g++
      - -DCMAKE_INSTALL_PREFIX={{prefix}}
      - -DCMAKE_INSTALL_SYSCONFDIR={{prefix}}/etc
      - -DCMAKE_INSTALL_SHAREDSTATEDIR={{prefix}}/var/lib
      - -DCMAKE_INSTALL_LOCALSTATEDIR={{prefix}}/var
      - -DENABLE_NLS=ON
      - -DENABLE_PLUGINS=OFF
      - -DWITH_AUDIT=OFF
      - -DWITH_SELINUX=OFF
      - -DRPM_VENDOR=pkgx
      - -DENABLE_TESTSUITE=OFF
      - -DWITH_ACL=OFF
      - -DWITH_CAP=OFF
  working-directory: build
  script:
    - run:
        - curl -L "https://github.com/rpm-software-management/rpm-sequoia/archive/refs/tags/v1.10.1.tar.gz" | tar zxvf - --strip-components=1
        - cargo build --release --no-default-features --features crypto-openssl
        - mkdir -p {{prefix}}/lib/pkgconfig
        - install -Dm644 target/release/librpm_sequoia.so {{prefix}}/lib/
        - ln -sf librpm_sequoia.so {{prefix}}/lib/librpm_sequoia.so.1
        - sed 's|/usr/local|${pcfiledir}/../..|' target/release/rpm-sequoia.pc >{{prefix}}/lib/pkgconfig/rpm-sequoia.pc
        - export PKG_CONFIG_PATH="{{prefix}}/lib/pkgconfig:$PKG_CONFIG_PATH"
        - export LIBRARY_PATH="{{prefix}}/lib:$LIBRARY_PATH"
        - export LD_LIBRARY_PATH="{{prefix}}/lib:$LD_LIBRARY_PATH"
      working-directory: r-s
    - cmake .. $CMAKE_ARGS
    - cmake --build .
    - cmake --install .

runtime:
  env:
    RPM_CONFIGDIR: "{{prefix}}/lib/rpm"

provides:
  - bin/rpm

test: test "$(rpm --version)" = "RPM version {{version}}"
