# cleans up our issues based on tags applied

name: library bot
run-name: "handling #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"

on:
  issues:
    types: [labeled]

jobs:
  close-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Close reason
        id: close-reason
        run: |
          case "${{ github.event.label.name }}" in
          "old-version"|"yanked")
            echo "reason=not_planned" >>$GITHUB_OUTPUT
            ;;
          "gha-issue"|"404"|"version-lockstep-required")
            echo "reason=completed" >>$GITHUB_OUTPUT
            ;;
          esac
      - name: Close issue
        if: steps.close-reason.outputs.reason != ''
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          CLOSE_REASON: ${{ steps.close-reason.outputs.reason }}
        run: |
          gh api \
            --method PATCH \
            "repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}" \
            -f state=closed \
            -f state_reason="${CLOSE_REASON}"
